include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - prefer_const_declarations
    - prefer_const_constructors
    - constant_identifier_names
    - prefer_constructors_over_static_methods
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_typing_uninitialized_variables
    - unnecessary_brace_in_string_interps
    - unnecessary_null_checks
    - unnecessary_this
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - valid_regexps