name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies: 
  bloc: ^8.0.3
  build_runner: ^2.7.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.1
  dio: ^5.9.0
  firebase_core: ^4.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  go_router: ^16.2.1
  injectable: ^2.5.1
  lottie: ^3.3.1
  pull_to_refresh_flutter3: ^2.0.2
  redacted: ^1.0.13
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.8.1


flutter:
  assets:
    - assets/fonts/montserrat/
    - assets/fonts/roboto/
    - assets/fonts/poppins/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-Light.ttf
  uses-material-design: true

flutter_assets:
  assets_path: assets/
  output_path: lib/core/assets/
  filename: app_icons.dart
  field_prefix:
